### PR TITLE
Refactor the code to the working condition

### PR DESCRIPTION
**Pull request by notgiorgi**
I separated the code in files, and made it to work.
After this I could implement tests and I think we can publish it.

## Notable changes:

- Only the actions which have truthy `action.meta.socket` and `action.payload.message` properties and are not incoming messages (have `action.meta.incoming` falsy) will be sent through the socket:

```js
export function isSocketAction (action) {
  return Boolean(
    action &&
    action.meta &&
    action.meta.socket &&
    action.payload &&
    action.payload.message
  )
}

export function isIncomingMessage (action) {
  return Boolean(action && action.meta && action.meta.incoming)
}
```

```js
if (!isSocketAction(action) || isIncomingMessage(action)) {
  return next(action)
}
```

- if `action.payload.message` is an object, middleware will `JSON.stringify` it:

```js
export function normalizeMessage (action) {
  const { payload: { message } } = action

  switch (typeof message) {
    case 'object':
      return JSON.stringify(message)
    default:
      return message
  }
}
```

- when `onmessage` is triggered, middleware tries to first parse message as json and if fails returns raw

### CODE REVIEW

**Comment by notgiorgi** [comment]
Also, currently middleware doesn't `next` actions with `meta.socket`, and probably we should, because those actions may contain data you need in reducers, to show spinner or something

**Comment by notgiorgi** [comment]
Probably we could send raw data by default and if user provides formatter, then decode/encode it using it.

**Comment by notgiorgi** [comment]
@sch ping

**Comment by sch** [comment]
Very nice work! I'm interested in the background that led to the `message` key of the payload. How are you using this field in your application?

**Comment by notgiorgi** [comment]
You mean, why `payload.message` and not `payload`? I though one might want to include other data in payload. Also I think, actions meant to be sent through socket, should be also "nexted", if we do that, it would be convenient.

https://github.com/sch/redux-websocket-middleware/pull/3#issuecomment-310381950

**Comment by notgiorgi** [comment]
How shall we proceed?

**Comment by notgiorgi** [comment]
I'm afraid if you're not willing to collaborate, I'd have to move the code into my own repo

**Pull request closed without merging**
